# Generated by Django 6.0.7 on 2026-09-13 10:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_patientprofile_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nurseprofile',
            name='nursing_type',
        ),
        migrations.AddField(
            model_name='cashierprofile',
            name='designation',
            field=models.CharField(blank=True, choices=[('FINANCE_MANAGER', 'Finance Manager'), ('SENIOR_CASHIER', 'Senior Cashier'), ('CASHIER', 'Cashier'), ('BILLING_EXECUTIVE', 'Billing Executive')], max_length=50),
        ),
        migrations.AddField(
            model_name='cashierprofile',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('FULL_TIME', 'Full Time'), ('PART_TIME', 'Part Time'), ('CONTRACT', 'Contract')], max_length=20),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='designation',
            field=models.CharField(blank=True, choices=[('HOD', 'Head of Department'), ('SENIOR_CONSULTANT', 'Senior Consultant'), ('CONSULTANT', 'Consultant'), ('ASSOCIATE_CONSULTANT', 'Associate Consultant'), ('SENIOR_RESIDENT', 'Senior Resident'), ('JUNIOR_RESIDENT', 'Junior Resident'), ('MEDICAL_OFFICER', 'Medical Officer')], max_length=50),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('FULL_TIME', 'Full Time'), ('PART_TIME', 'Part Time'), ('VISITING', 'Visiting'), ('CONTRACT', 'Contract')], max_length=20),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='joining_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labtechnicianprofile',
            name='designation',
            field=models.CharField(blank=True, choices=[('LAB_MANAGER', 'Lab Manager'), ('SENIOR_TECHNICIAN', 'Senior Lab Technician'), ('LAB_TECHNICIAN', 'Lab Technician'), ('JUNIOR_TECHNICIAN', 'Junior Lab Technician')], max_length=50),
        ),
        migrations.AddField(
            model_name='labtechnicianprofile',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('FULL_TIME', 'Full Time'), ('PART_TIME', 'Part Time'), ('CONTRACT', 'Contract')], max_length=20),
        ),
        migrations.AddField(
            model_name='nurseprofile',
            name='designation',
            field=models.CharField(blank=True, choices=[('HEAD_NURSE', 'Head Nurse'), ('SENIOR_NURSE', 'Senior Nurse'), ('STAFF_NURSE', 'Staff Nurse'), ('JUNIOR_NURSE', 'Junior Nurse')], max_length=50),
        ),
        migrations.AddField(
            model_name='nurseprofile',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('FULL_TIME', 'Full Time'), ('PART_TIME', 'Part Time'), ('CONTRACT', 'Contract')], max_length=20),
        ),
        migrations.AddField(
            model_name='nurseprofile',
            name='joining_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='occupation',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='pharmacistprofile',
            name='designation',
            field=models.CharField(blank=True, choices=[('PHARMACY_MANAGER', 'Pharmacy Manager'), ('PHARMACIST', 'Pharmacist'), ('JUNIOR_PHARMACIST', 'Junior Pharmacist')], max_length=50),
        ),
        migrations.AddField(
            model_name='pharmacistprofile',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('FULL_TIME', 'Full Time'), ('PART_TIME', 'Part Time'), ('CONTRACT', 'Contract')], max_length=20),
        ),
        migrations.AddField(
            model_name='receptionistprofile',
            name='designation',
            field=models.CharField(blank=True, choices=[('RECEPTION_MANAGER', 'Reception Manager'), ('SENIOR_RECEPTIONIST', 'Senior Receptionist'), ('RECEPTIONIST', 'Receptionist'), ('FRONT_DESK_EXECUTIVE', 'Front Desk Executive')], max_length=50),
        ),
        migrations.AddField(
            model_name='receptionistprofile',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('FULL_TIME', 'Full Time'), ('PART_TIME', 'Part Time'), ('CONTRACT', 'Contract')], max_length=20),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3),
        ),
        migrations.CreateModel(
            name='HospitalAdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('profile_picture', models.ImageField(null=True, upload_to='uploads/images')),
                ('address_line_1', models.CharField(max_length=100)),
                ('address_line_2', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('postal_code', models.IntegerField(validators=[django.core.validators.MinValueValidator(6), django.core.validators.MaxValueValidator(6)])),
                ('emergency_contact_name', models.CharField(max_length=10)),
                ('emergency_contact_phone', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('designation', models.CharField(choices=[('HOSPITAL_ADMINISTRATOR', 'Hospital Administrator'), ('OPERATIONS_MANAGER', 'Operations Manager'), ('ADMINISTRATIVE_MANAGER', 'Administrative Manager'), ('MEDICAL_SUPERINTENDENT', 'Medical Superintendent')], max_length=50, null=True)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
