# Generated by Django 6.0.7 on 2026-08-29 06:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('profile_picture', models.ImageField(null=True, upload_to='uploads/images')),
                ('address_line_1', models.CharField(max_length=100)),
                ('address_line_2', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('postal_code', models.IntegerField(validators=[django.core.validators.MinValueValidator(6), django.core.validators.MaxValueValidator(6)])),
                ('emergency_contact_name', models.CharField(max_length=10)),
                ('emergency_contact_phone', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Hospita Admin', 'Hospital Admin'), ('Doctor', 'Doctor'), ('Nurse', 'Nurse'), ('Receptionist', 'Receptionist'), ('Lab Technician', 'Lab Technician'), ('Pharmacist', 'Pharmacist'), ('Cashier', 'Cashier'), ('Patient', 'Patient')], null=True),
        ),
        migrations.CreateModel(
            name='CashierProfile',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.basemodel')),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cashier_profile', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('accounts.basemodel',),
        ),
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.basemodel')),
                ('registration_number', models.CharField(max_length=100, unique=True)),
                ('specialization', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=255)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bio', models.TextField(blank=True)),
                ('is_available', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('accounts.basemodel',),
        ),
        migrations.CreateModel(
            name='HospitalAdminProfile',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.basemodel')),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('designation', models.CharField(blank=True, max_length=100)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('accounts.basemodel',),
        ),
        migrations.CreateModel(
            name='LabTechnicianProfile',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.basemodel')),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('qualification', models.CharField(max_length=255)),
                ('specialization', models.CharField(blank=True, max_length=100)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lab_technician_profile', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('accounts.basemodel',),
        ),
        migrations.CreateModel(
            name='NurseProfile',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.basemodel')),
                ('registration_number', models.CharField(max_length=100, unique=True)),
                ('qualification', models.CharField(max_length=255)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('nursing_type', models.CharField(blank=True, max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nurse_profile', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('accounts.basemodel',),
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.basemodel')),
                ('patient_number', models.CharField(max_length=50, unique=True)),
                ('blood_group', models.CharField(blank=True, max_length=5)),
                ('address', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('accounts.basemodel',),
        ),
        migrations.CreateModel(
            name='PharmacistProfile',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.basemodel')),
                ('license_number', models.CharField(max_length=100, unique=True)),
                ('qualification', models.CharField(max_length=255)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacist_profile', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('accounts.basemodel',),
        ),
        migrations.CreateModel(
            name='ReceptionistProfile',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.basemodel')),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('qualification', models.CharField(blank=True, max_length=255)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receptionist_profile', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('accounts.basemodel',),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
