# Generated by Django 6.0.7 on 2026-09-01 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HospitalAdminProfile',
        ),
    ]
