# Generated by Django 6.0.7 on 2026-09-16 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_is_varified_user_is_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('HA', 'Hospital Admin'), ('DOC', 'Doctor'), ('NUR', 'Nurse'), ('REC', 'Receptionist'), ('LT', 'Lab Technician'), ('PHA', 'Pharmacist'), ('CAS', 'Cashier'), ('PATPatient', 'Patient')], null=True),
        ),
    ]
