# Generated by Django 6.0.7 on 2026-09-16 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('HA', 'Hospital_Admin'), ('DOC', 'Doctor'), ('NUR', 'Nurse'), ('REC', 'Receptionist'), ('LT', 'Lab_Technician'), ('PHA', 'Pharmacist'), ('CAS', 'Cashier'), ('PAT', 'Patient')], null=True),
        ),
    ]
