# Generated by Django 6.0.7 on 2026-09-20 15:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_cashierprofile_postal_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashierprofile',
            name='address_line_1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cashierprofile',
            name='address_line_2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cashierprofile',
            name='city',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='cashierprofile',
            name='country',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='cashierprofile',
            name='emergency_contact_name',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='cashierprofile',
            name='emergency_contact_phone',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cashierprofile',
            name='postal_code',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(100000), django.core.validators.MaxValueValidator(999999)]),
        ),
        migrations.AlterField(
            model_name='cashierprofile',
            name='state',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='address_line_1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='address_line_2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='city',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='country',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='emergency_contact_name',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='emergency_contact_phone',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='postal_code',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(100000), django.core.validators.MaxValueValidator(999999)]),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='state',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hospitaladminprofile',
            name='address_line_1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hospitaladminprofile',
            name='address_line_2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hospitaladminprofile',
            name='city',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='hospitaladminprofile',
            name='country',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='hospitaladminprofile',
            name='emergency_contact_name',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='hospitaladminprofile',
            name='emergency_contact_phone',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hospitaladminprofile',
            name='postal_code',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(100000), django.core.validators.MaxValueValidator(999999)]),
        ),
        migrations.AlterField(
            model_name='hospitaladminprofile',
            name='state',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='labtechnicianprofile',
            name='address_line_1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='labtechnicianprofile',
            name='address_line_2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='labtechnicianprofile',
            name='city',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='labtechnicianprofile',
            name='country',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='labtechnicianprofile',
            name='emergency_contact_name',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='labtechnicianprofile',
            name='emergency_contact_phone',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='labtechnicianprofile',
            name='postal_code',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(100000), django.core.validators.MaxValueValidator(999999)]),
        ),
        migrations.AlterField(
            model_name='labtechnicianprofile',
            name='state',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='nurseprofile',
            name='address_line_1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='nurseprofile',
            name='address_line_2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='nurseprofile',
            name='city',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='nurseprofile',
            name='country',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='nurseprofile',
            name='emergency_contact_name',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='nurseprofile',
            name='emergency_contact_phone',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='nurseprofile',
            name='postal_code',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(100000), django.core.validators.MaxValueValidator(999999)]),
        ),
        migrations.AlterField(
            model_name='nurseprofile',
            name='state',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='address_line_1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='address_line_2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='city',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='country',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='emergency_contact_name',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='emergency_contact_phone',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='postal_code',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(100000), django.core.validators.MaxValueValidator(999999)]),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='state',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='pharmacistprofile',
            name='address_line_1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pharmacistprofile',
            name='address_line_2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pharmacistprofile',
            name='city',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='pharmacistprofile',
            name='country',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='pharmacistprofile',
            name='emergency_contact_name',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pharmacistprofile',
            name='emergency_contact_phone',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pharmacistprofile',
            name='postal_code',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(100000), django.core.validators.MaxValueValidator(999999)]),
        ),
        migrations.AlterField(
            model_name='pharmacistprofile',
            name='state',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='receptionistprofile',
            name='address_line_1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='receptionistprofile',
            name='address_line_2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='receptionistprofile',
            name='city',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='receptionistprofile',
            name='country',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='receptionistprofile',
            name='emergency_contact_name',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='receptionistprofile',
            name='emergency_contact_phone',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='receptionistprofile',
            name='postal_code',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(100000), django.core.validators.MaxValueValidator(999999)]),
        ),
        migrations.AlterField(
            model_name='receptionistprofile',
            name='state',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
