# Generated by Django 6.0.7 on 2026-10-02 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorschedule',
            name='slot_duration',
            field=models.PositiveIntegerField(default=15, help_text='Duration in minutes'),
            preserve_default=False,
        ),
    ]
