# Generated by Django 6.0.7 on 2026-10-02 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_cashierprofile_address_line_1_and_more'),
        ('appointments', '0002_doctorschedule_slot_duration'),
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='appointmentslot',
            name='unique_doctor_appointment_slot',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='appointment_slot',
        ),
        migrations.AddField(
            model_name='appointment',
            name='slot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='appointments.appointmentslot'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'Cancelled'), _negated=True), fields=('doctor', 'appointment_date', 'slot'), name='unique_active_appointment'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['Cancelled', 'Completed']), _negated=True), fields=('patient', 'doctor', 'appointment_date'), name='unique_active_patient_doctor_per_day'),
        ),
        migrations.RemoveField(
            model_name='appointmentslot',
            name='date',
        ),
        migrations.RemoveField(
            model_name='appointmentslot',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='appointmentslot',
            name='is_available',
        ),
    ]
