# Generated by Django 6.0.7 on 2026-09-01 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='admin',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='administered_hospital', to='hospital.hospitaladminprofile'),
        ),
    ]
