# Generated by Django 6.0.7 on 2026-09-12 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='branch',
            name='unique_branch_code_per_hospital',
        ),
        migrations.RemoveField(
            model_name='department',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='website',
        ),
        migrations.AddField(
            model_name='hospital',
            name='address_line_1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='address_line_2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='country',
            field=models.CharField(default='India', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='postal_code',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='state',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='floor',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.RemoveField(
            model_name='branch',
            name='hospital',
        ),
        migrations.DeleteModel(
            name='HospitalAdminProfile',
        ),
        migrations.DeleteModel(
            name='Branch',
        ),
    ]
