# Generated by Django 6.0.7 on 2026-09-12 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_alter_department_code_alter_department_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hospital',
        ),
    ]
